export interface InterviewQuestion {
  id: string;
  stage: "algorithm" | "project" | "cross" | "hr";
  difficulty: "easy" | "medium" | "hard";
  title: string;
  content: string;
  tags: string[];
  company?: string;
  role?: string;
}

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // ========== 字节跳动 ==========
  {
    id: "byte-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "LRU 缓存机制",
    content: "设计并实现一个 LRU（最近最少使用）缓存，支持 get(key) 和 put(key, value) 操作，要求 O(1) 时间复杂度。如果缓存达到容量上限，淘汰最久未使用的键。",
    tags: ["数据结构", "哈希表", "双向链表"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-algo-02",
    stage: "algorithm",
    difficulty: "medium",
    title: "无重复字符的最长子串",
    content: "给定一个字符串 s，找出其中不含有重复字符的最长子串的长度。要求分析滑动窗口的时间复杂度，并讨论如何处理 Unicode 字符。",
    tags: ["滑动窗口", "哈希表", "字符串"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-algo-03",
    stage: "algorithm",
    difficulty: "hard",
    title: "接雨水",
    content: "给定 n 个非负整数表示每个宽度为 1 的柱子的高度图，计算按此排列的柱子下雨之后能接多少雨水。要求同时给出双指针和单调栈两种解法，并分析空间复杂度差异。",
    tags: ["双指针", "单调栈", "动态规划"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-algo-04",
    stage: "algorithm",
    difficulty: "hard",
    title: "合并 K 个升序链表",
    content: "给你一个链表数组，每个链表都已经按升序排列。将所有链表合并到一个升序链表中，返回合并后的链表。要求分析分治法 vs 优先队列的优劣。",
    tags: ["链表", "分治", "堆"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "秒杀系统设计",
    content: "设计一个秒杀系统，QPS 峰值 100 万。请讨论：库存扣减方案（Redis + Lua）、流量削峰（消息队列）、限流策略（令牌桶/漏桶）、数据一致性保证。",
    tags: ["系统设计", "高并发", "Redis", "消息队列"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  // ========== 阿里巴巴 ==========
  {
    id: "ali-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "岛屿数量",
    content: "给定一个由 '1'（陆地）和 '0'（水）组成的二维网格，计算网格中岛屿的数量。请同时给出 DFS 和 BFS 两种解法，并分析在大规模网格中哪个更优。",
    tags: ["DFS", "BFS", "图"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "ali-algo-02",
    stage: "algorithm",
    difficulty: "hard",
    title: "LFU 缓存",
    content: "设计一个 LFU（最不经常使用）缓存的数据结构。实现 get 和 put，当缓存达到容量限制时，移除使用频率最低的键；频率相同时移除最久未使用的。",
    tags: ["数据结构", "哈希表", "红黑树"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "ali-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "分布式事务方案",
    content: "在微服务架构中如何保证跨服务的分布式事务一致性？请详细讨论：两阶段提交、TCC 模式、最终一致性和可靠消息方案，以及各自的适用场景和缺陷。",
    tags: ["分布式系统", "事务", "微服务"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "ali-cross-01",
    stage: "cross",
    difficulty: "medium",
    title: "数据库分库分表",
    content: "当单表数据量超过 5000 万行时，请设计一个分库分表方案。讨论：分片键如何选择、跨分片查询如何处理、全局唯一 ID 生成方案、数据迁移和扩容策略。",
    tags: ["数据库", "分库分表", "分布式"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  // ========== 腾讯 ==========
  {
    id: "tx-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "二叉树的最近公共祖先",
    content: "给定一个二叉树，找到该树中两个指定节点的最近公共祖先。要求分别实现递归和迭代两种方法，并分析各自的空间复杂度。",
    tags: ["二叉树", "递归", "DFS"],
    company: "腾讯",
    role: "后端开发工程师",
  },
  {
    id: "tx-proj-01",
    stage: "project",
    difficulty: "hard",
    title: "微信朋友圈架构",
    content: "设计微信朋友圈的后端架构，支持发布、Feed 流推送（推模式 vs 拉模式）、Timeline 聚合、点赞和评论的实时更新。讨论一致性、可用性和分区容错的权衡。",
    tags: ["系统设计", "Feed流", "分布式", "CAP定理"],
    company: "腾讯",
    role: "后端开发工程师",
  },
  {
    id: "tx-cross-01",
    stage: "cross",
    difficulty: "medium",
    title: "C++ 虚函数实现原理",
    content: "请详细解释 C++ 虚函数的底层实现机制，包括虚函数表的结构、动态绑定的过程、多重继承下的虚继承问题，以及和 Java 接口的区别。",
    tags: ["C++", "面向对象", "底层"],
    company: "腾讯",
    role: "后端开发工程师",
  },
  // ========== 美团 ==========
  {
    id: "mt-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "三数之和",
    content: "给你一个整数数组 nums，判断是否存在三元组满足 nums[i] + nums[j] + nums[k] == 0。找出所有和为 0 且不重复的三元组。要求分析去重策略和剪枝优化。",
    tags: ["双指针", "排序", "去重"],
    company: "美团",
  },
  {
    id: "mt-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "外卖配送调度系统",
    content: "设计一个外卖配送调度系统，核心是骑手-订单匹配算法。讨论：实时位置更新、路径规划、骑手负载均衡、超时预测、冷热数据分离存储方案。",
    tags: ["系统设计", "调度算法", "实时计算"],
    company: "美团",
    role: "后端开发工程师",
  },
  // ========== 华为 ==========
  {
    id: "hw-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "字符串解码",
    content: "给定一个经过编码的字符串，返回它解码后的字符串。编码规则为 k[encoded_string]，表示方括号中的 encoded_string 正好重复 k 次。要求处理嵌套编码，如 3[a2[c]] → accaccacc。",
    tags: ["字符串", "栈", "递归"],
    company: "华为",
  },
  {
    id: "hw-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "高可用系统设计原则",
    content: "设计一个要求 99.99% 可用性的在线服务。请讨论：多活架构、故障自动切换、熔断降级、流量调度、监控告警体系。结合你熟悉的分布式框架给出具体方案。",
    tags: ["系统设计", "高可用", "分布式"],
    company: "华为",
    role: "后端开发工程师",
  },
  {
    id: "hw-cross-01",
    stage: "cross",
    difficulty: "hard",
    title: "操作系统进程调度",
    content: "请深入解释操作系统的进程调度算法（CFS、RR、优先级调度），讨论多核场景下的负载均衡、NUMA 架构对调度的影响，以及 Linux 内核中 CFS 的具体实现。",
    tags: ["操作系统", "Linux", "调度"],
    company: "华为",
  },
  // ========== 百度 ==========
  {
    id: "bd-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "搜索旋转排序数组",
    content: "整数数组 nums 按升序排列，在某个未知下标旋转后，给定目标值 target。如果存在返回下标，否则返回 -1。要求 O(log n) 时间复杂度，并讨论二分查找的边界条件。",
    tags: ["二分查找", "数组"],
    company: "百度",
  },
  {
    id: "bd-proj-01",
    stage: "project",
    difficulty: "hard",
    title: "搜索引擎倒排索引",
    content: "设计一个小型的搜索引擎倒排索引系统。讨论：分词策略、倒排表结构（SkipList 优化）、相关性排序（TF-IDF / BM25）、增量索引更新、大规模数据的分布式方案。",
    tags: ["搜索引擎", "倒排索引", "分布式"],
    company: "百度",
    role: "后端开发工程师",
  },
  // ========== 网易 ==========
  {
    id: "ne-algo-01",
    stage: "algorithm",
    difficulty: "easy",
    title: "有效的括号",
    content: "给定一个只包括 '('，')'，'{'，'}'，'['，']' 的字符串 s，判断字符串是否有效。要求用栈实现，并讨论如果加入更多类型的括号如何扩展。",
    tags: ["栈", "字符串"],
    company: "网易",
  },
  // ========== 京东 ==========
  {
    id: "jd-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "最长递增子序列",
    content: "给你一个整数数组 nums，找到其中最长严格递增子序列的长度。要求给出 O(n log n) 的二分查找解法，并讨论如何扩展到输出具体的最长子序列。",
    tags: ["动态规划", "二分查找"],
    company: "京东",
  },
  {
    id: "jd-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "订单状态机设计",
    content: "设计一个电商订单状态机，涵盖创建、支付、发货、确认收货、退款等状态流转。讨论：如何保证状态转移的原子性、如何处理并发修改、如何设计事件溯源方案以便审计和对账。",
    tags: ["系统设计", "状态机", "并发控制"],
    company: "京东",
    role: "后端开发工程师",
  },

  // ========== 通用 HR 面 ==========
  {
    id: "hr-01",
    stage: "hr",
    difficulty: "medium",
    title: "职业规划与动机",
    content: "你为什么选择我们公司而不是其他大厂？请结合你的技术方向、职业规划和个人价值观来回答。追问：如果同时拿到多家 Offer，你的决策标准是什么？",
    tags: ["职业规划", "动机", "价值观"],
  },
  {
    id: "hr-02",
    stage: "hr",
    difficulty: "medium",
    title: "最大挑战与失败经历",
    content: "请分享一次你遇到的最大技术挑战或失败经历。当时怎么处理的？学到了什么？如果再遇到类似情况会怎么做？",
    tags: ["抗压能力", "反思", "成长"],
  },
  {
    id: "hr-03",
    stage: "hr",
    difficulty: "easy",
    title: "团队协作冲突",
    content: "描述一次你和团队成员在技术方案上有重大分歧的经历。你当时是如何表达观点、如何妥协或说服对方的？最终结果如何？",
    tags: ["团队协作", "沟通", "冲突处理"],
  },
  {
    id: "hr-04",
    stage: "hr",
    difficulty: "medium",
    title: "薪资期望与职业选择",
    content: "你对薪资的期望是多少？除了薪资，你在选择工作时最看重的三个因素是什么？请举例说明。",
    tags: ["薪资", "职业规划", "价值观"],
  },
];

export const TOTAL_QUESTIONS = INTERVIEW_QUESTIONS.length;
