export interface InterviewQuestion {
  id: string;
  stage: "algorithm" | "project" | "cross" | "hr";
  difficulty: "easy" | "medium" | "hard";
  title: string;
  content: string;
  tags: string[];
  company?: string;
  role?: string;
}

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // ========== 字节跳动 ==========
  {
    id: "byte-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "LRU 缓存机制",
    content: "设计并实现一个 LRU（最近最少使用）缓存，支持 get(key) 和 put(key, value) 操作，要求 O(1) 时间复杂度。如果缓存达到容量上限，淘汰最久未使用的键。",
    tags: ["数据结构", "哈希表", "双向链表"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-algo-02",
    stage: "algorithm",
    difficulty: "medium",
    title: "无重复字符的最长子串",
    content: "给定一个字符串 s，找出其中不含有重复字符的最长子串的长度。要求分析滑动窗口的时间复杂度，并讨论如何处理 Unicode 字符。",
    tags: ["滑动窗口", "哈希表", "字符串"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-algo-03",
    stage: "algorithm",
    difficulty: "hard",
    title: "接雨水",
    content: "给定 n 个非负整数表示每个宽度为 1 的柱子的高度图，计算按此排列的柱子下雨之后能接多少雨水。要求同时给出双指针和单调栈两种解法，并分析空间复杂度差异。",
    tags: ["双指针", "单调栈", "动态规划"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-algo-04",
    stage: "algorithm",
    difficulty: "hard",
    title: "合并 K 个升序链表",
    content: "给你一个链表数组，每个链表都已经按升序排列。将所有链表合并到一个升序链表中，返回合并后的链表。要求分析分治法 vs 优先队列的优劣。",
    tags: ["链表", "分治", "堆"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "byte-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "秒杀系统设计",
    content: "设计一个秒杀系统，QPS 峰值 100 万。请讨论：库存扣减方案（Redis + Lua）、流量削峰（消息队列）、限流策略（令牌桶/漏桶）、数据一致性保证。",
    tags: ["系统设计", "高并发", "Redis", "消息队列"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  // ========== 阿里巴巴 ==========
  {
    id: "ali-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "岛屿数量",
    content: "给定一个由 '1'（陆地）和 '0'（水）组成的二维网格，计算网格中岛屿的数量。请同时给出 DFS 和 BFS 两种解法，并分析在大规模网格中哪个更优。",
    tags: ["DFS", "BFS", "图"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "ali-algo-02",
    stage: "algorithm",
    difficulty: "hard",
    title: "LFU 缓存",
    content: "设计一个 LFU（最不经常使用）缓存的数据结构。实现 get 和 put，当缓存达到容量限制时，移除使用频率最低的键；频率相同时移除最久未使用的。",
    tags: ["数据结构", "哈希表", "红黑树"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "ali-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "分布式事务方案",
    content: "在微服务架构中如何保证跨服务的分布式事务一致性？请详细讨论：两阶段提交、TCC 模式、最终一致性和可靠消息方案，以及各自的适用场景和缺陷。",
    tags: ["分布式系统", "事务", "微服务"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "ali-cross-01",
    stage: "cross",
    difficulty: "medium",
    title: "数据库分库分表",
    content: "当单表数据量超过 5000 万行时，请设计一个分库分表方案。讨论：分片键如何选择、跨分片查询如何处理、全局唯一 ID 生成方案、数据迁移和扩容策略。",
    tags: ["数据库", "分库分表", "分布式"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  // ========== 腾讯 ==========
  {
    id: "tx-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "二叉树的最近公共祖先",
    content: "给定一个二叉树，找到该树中两个指定节点的最近公共祖先。要求分别实现递归和迭代两种方法，并分析各自的空间复杂度。",
    tags: ["二叉树", "递归", "DFS"],
    company: "腾讯",
    role: "后端开发工程师",
  },
  {
    id: "tx-proj-01",
    stage: "project",
    difficulty: "hard",
    title: "微信朋友圈架构",
    content: "设计微信朋友圈的后端架构，支持发布、Feed 流推送（推模式 vs 拉模式）、Timeline 聚合、点赞和评论的实时更新。讨论一致性、可用性和分区容错的权衡。",
    tags: ["系统设计", "Feed流", "分布式", "CAP定理"],
    company: "腾讯",
    role: "后端开发工程师",
  },
  {
    id: "tx-cross-01",
    stage: "cross",
    difficulty: "medium",
    title: "C++ 虚函数实现原理",
    content: "请详细解释 C++ 虚函数的底层实现机制，包括虚函数表的结构、动态绑定的过程、多重继承下的虚继承问题，以及和 Java 接口的区别。",
    tags: ["C++", "面向对象", "底层"],
    company: "腾讯",
    role: "后端开发工程师",
  },
  // ========== 美团 ==========
  {
    id: "mt-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "三数之和",
    content: "给你一个整数数组 nums，判断是否存在三元组满足 nums[i] + nums[j] + nums[k] == 0。找出所有和为 0 且不重复的三元组。要求分析去重策略和剪枝优化。",
    tags: ["双指针", "排序", "去重"],
    company: "美团",
  },
  {
    id: "mt-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "外卖配送调度系统",
    content: "设计一个外卖配送调度系统，核心是骑手-订单匹配算法。讨论：实时位置更新、路径规划、骑手负载均衡、超时预测、冷热数据分离存储方案。",
    tags: ["系统设计", "调度算法", "实时计算"],
    company: "美团",
    role: "后端开发工程师",
  },
  // ========== 华为 ==========
  {
    id: "hw-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "字符串解码",
    content: "给定一个经过编码的字符串，返回它解码后的字符串。编码规则为 k[encoded_string]，表示方括号中的 encoded_string 正好重复 k 次。要求处理嵌套编码，如 3[a2[c]] → accaccacc。",
    tags: ["字符串", "栈", "递归"],
    company: "华为",
  },
  {
    id: "hw-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "高可用系统设计原则",
    content: "设计一个要求 99.99% 可用性的在线服务。请讨论：多活架构、故障自动切换、熔断降级、流量调度、监控告警体系。结合你熟悉的分布式框架给出具体方案。",
    tags: ["系统设计", "高可用", "分布式"],
    company: "华为",
    role: "后端开发工程师",
  },
  {
    id: "hw-cross-01",
    stage: "cross",
    difficulty: "hard",
    title: "操作系统进程调度",
    content: "请深入解释操作系统的进程调度算法（CFS、RR、优先级调度），讨论多核场景下的负载均衡、NUMA 架构对调度的影响，以及 Linux 内核中 CFS 的具体实现。",
    tags: ["操作系统", "Linux", "调度"],
    company: "华为",
  },
  // ========== 百度 ==========
  {
    id: "bd-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "搜索旋转排序数组",
    content: "整数数组 nums 按升序排列，在某个未知下标旋转后，给定目标值 target。如果存在返回下标，否则返回 -1。要求 O(log n) 时间复杂度，并讨论二分查找的边界条件。",
    tags: ["二分查找", "数组"],
    company: "百度",
  },
  {
    id: "bd-proj-01",
    stage: "project",
    difficulty: "hard",
    title: "搜索引擎倒排索引",
    content: "设计一个小型的搜索引擎倒排索引系统。讨论：分词策略、倒排表结构（SkipList 优化）、相关性排序（TF-IDF / BM25）、增量索引更新、大规模数据的分布式方案。",
    tags: ["搜索引擎", "倒排索引", "分布式"],
    company: "百度",
    role: "后端开发工程师",
  },
  // ========== 网易 ==========
  {
    id: "ne-algo-01",
    stage: "algorithm",
    difficulty: "easy",
    title: "有效的括号",
    content: "给定一个只包括 '('，')'，'{'，'}'，'['，']' 的字符串 s，判断字符串是否有效。要求用栈实现，并讨论如果加入更多类型的括号如何扩展。",
    tags: ["栈", "字符串"],
    company: "网易",
  },
  // ========== 京东 ==========
  {
    id: "jd-algo-01",
    stage: "algorithm",
    difficulty: "medium",
    title: "最长递增子序列",
    content: "给你一个整数数组 nums，找到其中最长严格递增子序列的长度。要求给出 O(n log n) 的二分查找解法，并讨论如何扩展到输出具体的最长子序列。",
    tags: ["动态规划", "二分查找"],
    company: "京东",
  },
  {
    id: "jd-proj-01",
    stage: "project",
    difficulty: "medium",
    title: "订单状态机设计",
    content: "设计一个电商订单状态机，涵盖创建、支付、发货、确认收货、退款等状态流转。讨论：如何保证状态转移的原子性、如何处理并发修改、如何设计事件溯源方案以便审计和对账。",
    tags: ["系统设计", "状态机", "并发控制"],
    company: "京东",
    role: "后端开发工程师",
  },

  // ========== 通用 HR 面 ==========
  {
    id: "hr-01",
    stage: "hr",
    difficulty: "medium",
    title: "职业规划与动机",
    content: "你为什么选择我们公司而不是其他大厂？请结合你的技术方向、职业规划和个人价值观来回答。追问：如果同时拿到多家 Offer，你的决策标准是什么？",
    tags: ["职业规划", "动机", "价值观"],
  },
  {
    id: "hr-02",
    stage: "hr",
    difficulty: "medium",
    title: "最大挑战与失败经历",
    content: "请分享一次你遇到的最大技术挑战或失败经历。当时怎么处理的？学到了什么？如果再遇到类似情况会怎么做？",
    tags: ["抗压能力", "反思", "成长"],
  },
  {
    id: "hr-03",
    stage: "hr",
    difficulty: "easy",
    title: "团队协作冲突",
    content: "描述一次你和团队成员在技术方案上有重大分歧的经历。你当时是如何表达观点、如何妥协或说服对方的？最终结果如何？",
    tags: ["团队协作", "沟通", "冲突处理"],
  },
  {
    id: "hr-04",
    stage: "hr",
    difficulty: "medium",
    title: "薪资期望与职业选择",
    content: "你对薪资的期望是多少？除了薪资，你在选择工作时最看重的三个因素是什么？请举例说明。",
    tags: ["薪资", "职业规划", "价值观"],
  },

  // ========== 补充算法题 ==========
  {
    id: "algo-extra-01",
    stage: "algorithm",
    difficulty: "easy",
    title: "两数之和",
    content: "给定一个整数数组 nums 和一个整数目标值 target，找出数组中和为目标值的两个数的下标。要求给出 O(n) 的哈希表解法，并讨论如果要求返回所有组合如何处理。",
    tags: ["哈希表", "数组"],
    company: "字节跳动",
  },
  {
    id: "algo-extra-02",
    stage: "algorithm",
    difficulty: "medium",
    title: "环形链表检测",
    content: "给定一个链表，判断链表中是否有环。如果有环，找到环的入口节点。要求用快慢指针实现 O(1) 空间复杂度，并数学证明为什么相遇后从头再走会在入口相遇。",
    tags: ["链表", "双指针", "数学"],
    company: "美团",
  },
  {
    id: "algo-extra-03",
    stage: "algorithm",
    difficulty: "medium",
    title: "全排列",
    content: "给定一个不含重复数字的数组 nums，返回其所有可能的全排列。要求用回溯算法实现，并讨论剪枝策略和去重方法（如果 nums 包含重复数字怎么处理）。",
    tags: ["回溯", "DFS", "剪枝"],
    company: "腾讯",
  },
  {
    id: "algo-extra-04",
    stage: "algorithm",
    difficulty: "medium",
    title: "最大子数组和",
    content: "给定一个整数数组 nums，找出一个具有最大和的连续子数组。要求给出 Kadane 算法的 O(n) 解法，并扩展到允许包含最多 k 个负数的情况。",
    tags: ["动态规划", "分治", "贪心"],
    company: "百度",
  },
  {
    id: "algo-extra-05",
    stage: "algorithm",
    difficulty: "hard",
    title: "编辑距离",
    content: "给定两个单词 word1 和 word2，计算将 word1 转换成 word2 所使用的最少操作数。允许的操作：插入、删除、替换。要求分析动态规划状态转移方程，并讨论如何优化到 O(n) 空间。",
    tags: ["动态规划", "字符串"],
    company: "华为",
  },
  {
    id: "algo-extra-06",
    stage: "algorithm",
    difficulty: "medium",
    title: "二叉树的层序遍历",
    content: "给定一个二叉树，返回其按层序遍历得到的节点值（即逐层从左到右）。要求给出 BFS 队列解法，并扩展到 Zigzag 锯齿形遍历。",
    tags: ["二叉树", "BFS", "队列"],
    company: "网易",
  },
  {
    id: "algo-extra-07",
    stage: "algorithm",
    difficulty: "hard",
    title: "正则表达式匹配",
    content: "实现正则表达式匹配，支持 '.' 和 '*'。'.' 匹配任意单个字符，'*' 匹配零个或多个前面的元素。要求分析动态规划解法的时间空间复杂度。",
    tags: ["动态规划", "字符串", "递归"],
    company: "京东",
  },
  {
    id: "algo-extra-08",
    stage: "algorithm",
    difficulty: "medium",
    title: "前 K 个高频元素",
    content: "给定一个非空的整数数组，返回其中出现频率前 k 高的元素。要求给出时间复杂度优于 O(n log n) 的解法（提示：桶排序或堆）。",
    tags: ["堆", "桶排序", "哈希表"],
    company: "阿里巴巴",
  },
  {
    id: "algo-extra-09",
    stage: "algorithm",
    difficulty: "medium",
    title: "单词搜索",
    content: "给定一个 m×n 二维字符网格 board 和一个字符串 word，判断网格中是否存在一条包含 word 所有字符的路径。路径不能重复使用同一个格子。要求用 DFS + 回溯实现。",
    tags: ["DFS", "回溯", "剪枝"],
    company: "字节跳动",
  },
  {
    id: "algo-extra-10",
    stage: "algorithm",
    difficulty: "hard",
    title: "数据流的中位数",
    content: "设计一个支持以下操作的数据结构：addNum(num) 从数据流中添加整数，findMedian() 返回目前所有元素的中位数。要求两个方法的时间复杂度都不超过 O(log n)。",
    tags: ["堆", "设计", "数据流"],
    company: "腾讯",
  },
  {
    id: "algo-extra-11",
    stage: "algorithm",
    difficulty: "medium",
    title: "二叉搜索树验证",
    content: "给定一个二叉树的根节点 root，判断其是否是一个有效的二叉搜索树。要求同时给出递归（利用上下界）和中序遍历两种解法，并分析各自的优劣。",
    tags: ["二叉树", "BST", "中序遍历"],
    company: "阿里巴巴",
  },
  {
    id: "algo-extra-12",
    stage: "algorithm",
    difficulty: "hard",
    title: "单词拆分 II",
    content: "给定一个字符串 s 和一个字符串字典 wordDict，在 s 中增加空格构建句子，使得句子中所有单词都在字典中。返回所有可能的句子。要求分析回溯 + 记忆化搜索的复杂度。",
    tags: ["动态规划", "回溯", "记忆化"],
    company: "美团",
  },
  {
    id: "algo-extra-13",
    stage: "algorithm",
    difficulty: "medium",
    title: "寻找峰值",
    content: "峰值元素是指其值严格大于左右相邻值的元素。给定一个整数数组 nums，找到峰值元素并返回其索引。要求给出 O(log n) 的二分查找解法。",
    tags: ["二分查找", "数组"],
    company: "百度",
  },
  {
    id: "algo-extra-14",
    stage: "algorithm",
    difficulty: "medium",
    title: "零钱兑换",
    content: "给定不同面额的硬币 coins 和一个总金额 amount。计算可以凑成总金额所需的最少硬币个数。如果没有任何组合能组成总金额，返回 -1。要求分析 BFS 和 DP 两种解法的优劣。",
    tags: ["动态规划", "BFS", "贪心"],
    company: "京东",
  },
  {
    id: "algo-extra-15",
    stage: "algorithm",
    difficulty: "hard",
    title: "滑动窗口最大值",
    content: "给定一个整数数组 nums，有一个大小为 k 的滑动窗口从数组最左侧移动到最右侧。返回滑动窗口在每个位置时的最大值。要求用单调队列实现 O(n) 时间复杂度。",
    tags: ["滑动窗口", "单调队列", "双端队列"],
    company: "华为",
  },

  // ========== 补充项目/系统设计题 ==========
  {
    id: "proj-extra-01",
    stage: "project",
    difficulty: "hard",
    title: "短链接系统设计",
    content: "设计一个类似 t.cn 的短链接服务。讨论：哈希算法选型（Base62、MurmurHash）、冲突处理、分布式 ID 生成（Snowflake）、缓存策略、301 vs 302 重定向选择、以及如何支持自定义短链接。预估日活 1 亿的存储容量。",
    tags: ["系统设计", "分布式ID", "缓存", "哈希"],
    company: "字节跳动",
    role: "后端开发工程师",
  },
  {
    id: "proj-extra-02",
    stage: "project",
    difficulty: "medium",
    title: "接口限流方案",
    content: "你的服务需要对某个 API 接口做限流保护。请对比：固定窗口计数器、滑动窗口日志、令牌桶算法和漏桶算法。用 Redis + Lua 脚本实现一个精确的分布式滑动窗口限流器。",
    tags: ["限流", "Redis", "算法"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "proj-extra-03",
    stage: "project",
    difficulty: "medium",
    title: "MySQL 索引优化案例",
    content: "一条慢 SQL 查询需要 5 秒。表有 500 万行数据。请描述你的排查思路：EXPLAIN 分析、覆盖索引、联合索引最左匹配、索引下推、回表优化。给出具体的索引设计方案和验证方法。",
    tags: ["MySQL", "索引", "SQL优化"],
    company: "京东",
    role: "后端开发工程师",
  },
  {
    id: "proj-extra-04",
    stage: "project",
    difficulty: "medium",
    title: "消息队列选型",
    content: "对比 Kafka、RocketMQ 和 RabbitMQ 的架构差异和适用场景。分别讨论它们在吞吐量、延迟、消息可靠性、顺序消息、事务消息方面的表现。如果你的业务需要严格顺序 + 事务，选哪个？为什么？",
    tags: ["消息队列", "Kafka", "RocketMQ", "系统设计"],
    company: "美团",
    role: "后端开发工程师",
  },
  {
    id: "proj-extra-05",
    stage: "project",
    difficulty: "hard",
    title: "API 网关设计",
    content: "设计一个支持日请求量 100 亿的 API 网关。需要实现：路由转发、协议转换、限流熔断、身份认证、日志审计、灰度发布、API 版本管理。给出整体架构图并讨论各组件的高可用方案。",
    tags: ["网关", "高并发", "微服务", "系统设计"],
    company: "腾讯",
    role: "后端开发工程师",
  },
  {
    id: "proj-extra-06",
    stage: "project",
    difficulty: "medium",
    title: "缓存穿透/击穿/雪崩",
    content: "解释缓存穿透、缓存击穿和缓存雪崩的区别。针对每种场景给出 2-3 种解决方案（布隆过滤器、互斥锁、过期时间随机化、多级缓存），并讨论各自的适用条件和性能开销。",
    tags: ["缓存", "Redis", "高并发"],
    company: "百度",
    role: "后端开发工程师",
  },
  {
    id: "proj-extra-07",
    stage: "project",
    difficulty: "medium",
    title: "微服务拆分原则",
    content: "你接手了一个单体应用，需要拆分为微服务。请描述你的拆分策略：如何确定服务边界（DDD 限界上下文）、数据库如何拆分（每服务独立数据库 vs 共享数据库）、服务间通信方式（同步 RPC vs 异步消息）。",
    tags: ["微服务", "DDD", "架构"],
    company: "网易",
    role: "后端开发工程师",
  },
  {
    id: "proj-extra-08",
    stage: "project",
    difficulty: "hard",
    title: "排行榜系统设计",
    content: "设计一个千万用户级别的实时排行榜系统。支持：按积分排序、实时更新排名、查看 Top 100、查询指定用户排名及前后 10 名。对比 Redis Sorted Set、跳表、分段桶方案，给出选型理由和容量估算。",
    tags: ["排行榜", "Redis", "系统设计"],
    company: "华为",
    role: "后端开发工程师",
  },

  // ========== 补充交叉面题 ==========
  {
    id: "cross-extra-01",
    stage: "cross",
    difficulty: "hard",
    title: "分布式一致性协议",
    content: "请深入对比 Paxos 和 Raft 两种分布式一致性协议：领导者选举机制、日志复制过程、安全性保证、成员变更处理。为什么 Raft 更易于理解和工程实现？结合 etcd 或 TiKV 的源码谈谈你的理解。",
    tags: ["分布式系统", "一致性", "Paxos", "Raft"],
    company: "腾讯",
  },
  {
    id: "cross-extra-02",
    stage: "cross",
    difficulty: "medium",
    title: "服务降级策略",
    content: "在大促流量高峰时，你的核心服务出现性能瓶颈。请设计一个多级降级方案：哪些功能可以降级、降级开关如何设计（配置中心动态下发）、如何保证降级后的核心链路可用、如何做自动 vs 手动降级的决策。",
    tags: ["高可用", "降级", "架构"],
    company: "阿里巴巴",
    role: "后端开发工程师",
  },
  {
    id: "cross-extra-03",
    stage: "cross",
    difficulty: "medium",
    title: "全链路压测方案",
    content: "你想对核心交易链路进行全链路压测。讨论：流量录制回放、数据隔离（影子库/影子表）、流量染色、压测标记透传、如何保证压测不影响线上真实数据。你如何验证压测结果的可信度？",
    tags: ["压测", "全链路", "架构"],
    company: "美团",
  },
  {
    id: "cross-extra-04",
    stage: "cross",
    difficulty: "hard",
    title: "CAP 理论实践",
    content: "CAP 定理说分布式系统最多只能同时满足一致性、可用性和分区容错中的两个。请用你实际参与的项目举例，说明你在实践中如何权衡 CAP。讨论最终一致性的具体实现（如 CRDT、向量时钟）。",
    tags: ["分布式系统", "CAP定理", "一致性"],
    company: "华为",
  },
  {
    id: "cross-extra-05",
    stage: "cross",
    difficulty: "medium",
    title: "技术选型方法论",
    content: "你作为 Tech Lead 需要为一个新项目做技术选型。请描述你的决策框架：如何评估候选技术（社区活跃度、团队熟悉度、性能基准、长期维护成本）、如何做 POC 验证、如何输出选型文档让团队达成共识。",
    tags: ["技术管理", "选型", "团队"],
    company: "百度",
  },
  {
    id: "cross-extra-06",
    stage: "cross",
    difficulty: "medium",
    title: "日志与监控体系",
    content: "设计一个可观测性体系：日志采集（ELK/Loki）、指标监控（Prometheus + Grafana）、链路追踪（Jaeger/Zipkin）。你如何设置告警阈值、如何设计 Dashboard、如何从海量日志中快速定位线上问题？",
    tags: ["可观测性", "监控", "日志", "SRE"],
    company: "京东",
  },
  {
    id: "cross-extra-07",
    stage: "cross",
    difficulty: "medium",
    title: "Git 工作流与 Code Review",
    content: "描述你在团队中使用的 Git 工作流（GitFlow / GitHub Flow / Trunk-Based）。Code Review 时你最关注哪些方面（架构合理性、代码可读性、性能、安全性、测试覆盖）？如何推动团队形成高效的 CR 文化？",
    tags: ["工程化", "Git", "CodeReview"],
    company: "网易",
  },
  {
    id: "cross-extra-08",
    stage: "cross",
    difficulty: "hard",
    title: "数据一致性方案",
    content: "在电商场景中，用户下单后需要同时扣减库存、创建订单、扣减余额。分析 2PC、TCC、Saga 和本地消息表方案的优劣。如果余额服务暂时不可用，订单服务如何保证最终一致性？给出完整的异常恢复策略。",
    tags: ["分布式事务", "一致性", "电商"],
    company: "京东",
    role: "后端开发工程师",
  },

  // ========== 补充 HR 面 ==========
  {
    id: "hr-extra-01",
    stage: "hr",
    difficulty: "medium",
    title: "学习新技术的方法",
    content: "请举例说明你最近主动学习的一项新技术或新框架。你是怎么学的？遇到了什么困难？如何在项目中学以致用？你认为如何保持技术的持续学习？",
    tags: ["学习能力", "自驱力", "技术热情"],
  },
  {
    id: "hr-extra-02",
    stage: "hr",
    difficulty: "easy",
    title: "自我认知与改进",
    content: "如果要你用一个词形容自己最大的缺点，你会选什么？这个缺点在工作中给你带来过什么问题？你做了哪些努力来改善？",
    tags: ["自我认知", "反思", "成长"],
  },
  {
    id: "hr-extra-03",
    stage: "hr",
    difficulty: "medium",
    title: "领导力与影响力",
    content: "描述一次你主动推动一个想法或改进落地的经历，尽管当时你并没有正式的职权。你是如何说服相关方、如何克服阻力的？最终产生了什么影响？",
    tags: ["领导力", "影响力", "推动力"],
  },
  {
    id: "hr-extra-04",
    stage: "hr",
    difficulty: "medium",
    title: "技术热情与深度",
    content: "除了日常工作需要的技术，你有哪些自学的技术方向或 Side Project？请分享一个你觉得最有成就感的技术项目，它解决了什么问题？技术上的挑战是什么？",
    tags: ["技术热情", "项目", "工程化"],
  },
  {
    id: "hr-extra-05",
    stage: "hr",
    difficulty: "hard",
    title: "价值观冲突处理",
    content: "如果你的上级要求你在一个紧迫的时间节点上线一个质量不够完善的功能，而你认为这会给用户带来风险。你会怎么处理这种情况？请详细说明你的沟通策略和决策逻辑。",
    tags: ["价值观", "冲突处理", "权衡"],
  },
  {
    id: "hr-extra-06",
    stage: "hr",
    difficulty: "medium",
    title: "团队文化与贡献",
    content: "你希望在什么样的团队文化中工作？你在过往的团队中做了哪些行为来建设健康的团队文化（技术分享、文档建设、新人指导）？你如何看待技术人员的'软技能'？",
    tags: ["团队文化", "软技能", "贡献"],
  },
];

export const TOTAL_QUESTIONS = INTERVIEW_QUESTIONS.length;
